# Generated by Django 3.0.8 on 2021-01-27 15:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20210111_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='pin_code',
            field=models.CharField(max_length=5, unique=True, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
    ]
